FROM quay.io/fedora/fedora-bootc:44

RUN dnf update && dnf clean all

#NFS installation
RUN dnf install -y nfs-utils git && dnf clean all
RUN systemctl enable nfs-server rpcbind

RUN git clone https://github.com/ggml-org/llama.cpp
